Instead of returning nil, return string for unknown types
vapor-community/postgresql pull request #17
Opened 2016-10-22 22:09 UTC by sroebert

I am not really sure if this is the way to go, but this pull request changes the way unknown values are returned. Instead of returning `.null`, now the string is returned directly in a `Node`. This allows to work with custom PostgreSQL types as strings.

2016-10-22 22:18 UTC, sroebert commented
If this enhancement is approved as correct behaviour, I will add some unit tests for it.

2016-10-23 03:45 UTC, natebird commented
So you could use this for UUID, JSONB, and other unsupported types?

2016-10-23 07:25 UTC, sroebert commented
Exactly, I am using it in one of my projects for UUIDs. Considering Fluent doesn't support it yet, this will do for now. Also I think it is nicer to at least return the value, instead of just null, considering there is actually a value.

2016-10-23 13:43 UTC, natebird commented
I think this is a good idea. It allows support for types that aren't natively supported (yet). We can get @tannernelson to weigh in as well.

2016-10-24 20:43 UTC, tanner0101 requested changes
Could we add a test for this? Otherwise it's possible there could be regression.

2016-10-24 20:43 UTC, tannernelson commented on Sources/PostgreSQL/Node+Oid.swift
> +            // Always fallback to string, allowing to use with custom types as strings
Comment formatting appears a bit off here.

2016-10-24 20:59 UTC, sroebert commented on Sources/PostgreSQL/Node+Oid.swift
> +            // Always fallback to string, allowing to use with custom types as strings
Fixed

2016-10-24 21:31 UTC, sroebert commented
I added some more unit tests and reverted the `.string` for the `unknown` type. For the `unknown` type it does not really seem to make any sense. I could not even get any data in for that type.

2016-10-26 16:46 UTC, tanner0101 approved these changes

2016-10-26 16:46 UTC, tannernelson commented
LGTM, go ahead and tag

2016-10-26 16:48 UTC, merged