Add support for LISTEN and NOTIFY
vapor-community/postgresql pull request #29
Opened 2017-02-28 07:45 UTC by johnbona

I'm not all that comfortable with `libpq` so give this extra scrutiny. 🙊 

I used [this example](https://www.postgresql.org/docs/9.6/static/libpq-example.html#LIBPQ-EXAMPLE-2) heavily to help me determine how to receive notifications using `libpq`. I also purposefully broke convention and used a closure in `listen` instead of creating a `onNotification` property off `Database` since a database could be listening to multiple channels simultaneously.

Couple of things that I wanted to point out for feedback:
- What to do with errors caught in `listen` since the closure in `try background` can't throw? Using `fatalError` right now but not sure if that's the correct approach.
- The name of the `Notification` struct. It's not really meant to be used outside the `listen` closure so it's maybe okay to keep named as is even though it collides with Foundation's own `Notification`.

2017-03-04 03:37 UTC, natebird requested changes

2017-03-04 03:37 UTC, natebird commented on README.md
> +
This section is a good example of how to get it to work but can you provide some context before the example of why you would use listen and notify?

I'd also recommend linking to the docs for more detail. https://www.postgresql.org/docs/current/static/sql-notify.html

2017-03-04 03:37 UTC, natebird commented on Sources/PostgreSQL/Database.swift
>      }
I recommend moving the makeConnection function above the listen and notify functions. It will keep the flow of the document consistent.

2017-03-06 05:19 UTC, johnbona commented
@natebird Made the changes you requested and also found a slight performance increase using string concatenation instead of interpolation when constructing the SQL statements, especially for large `NOTIFY` payloads.

2017-04-05 02:50 UTC, natebird approved these changes

2017-04-05 02:51 UTC, natebird commented
@tanner0101 @LoganWright - do you know why CircleCI isn't responding to PRs on this repo?

2017-04-05 07:44 UTC, vzsg commented
Circle only responds to PRs which are started from this repo, not external forks.
I don't know why it's so.

The typical workaround for me was to push the other branch here and start a new PR - you should be able to do this with your permissions.

2017-04-05 11:52 UTC, natebird commented
@vzsg I figured out the issue. It is a setting in Circle. @johnbona can you push an empty commit to this branch again to kick Circle?

2017-04-05 12:07 UTC, vzsg commented
It's not going to help, as this PR is still originated from johnbona:feature/listen-and-notify.

2017-04-05 12:15 UTC, vzsg commented
Sorry, I couldn't resist :)

2017-04-05 12:21 UTC, natebird commented
Yay!

2017-04-05 16:30 UTC, natebird commented
@johnbona can you review this again? The tests are failing. 

Now that we have a 2.0 Beta release for this repo we can merge this PR into the 2.0 release.

Thanks!

2017-04-05 18:32 UTC, johnbona commented
@natebird Should be good now!

2017-04-06 02:23 UTC, merged